/*
AUTO-GENERATED FILE. DO NOT MODIFY.
This file was generated by Sequelize CLI.
*/
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import Sequelize from "sequelize";
import process from "process";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const env = process.env.NODE_ENV || "production";
const basename = path.basename(__filename);
const configModule = await import(pathToFileURL(path.resolve(__dirname, "../config/config.js")).href);
const config = (configModule.default || configModule)[env];
const db = {};

console.log(`Running in ${env} environment`);

let sequelize;
if (config.use_env_variable) {
  sequelize = new Sequelize(process.env[config.use_env_variable], config);
} else {
  sequelize = new Sequelize(config.database, config.username, config.password, config);
}

const files = fs.readdirSync(__dirname).filter((file) => {
  return file.indexOf(".") !== 0 && file !== basename && file.slice(-3) === ".js" && file.indexOf(".test.js") === -1;
});

for (const file of files) {
  const modelModule = await import(pathToFileURL(path.join(__dirname, file)).href);
  const model = (modelModule.default || modelModule)(sequelize, Sequelize.DataTypes);
  db[model.name] = model;
}

Object.keys(db).forEach((modelName) => {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

export default db;
